spring:
  application:
      name: service-dfsfile
server:
  port: 8771
  profiles:
    active: dev
#eruka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
#      register-with-eureka: false
#      #是否需要从eureka上获取注册信息
#      fetch-registry: false


###fastdfs配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  ###nginx反向监听storage服务配置，ip（nginx配置放在前台，后台只提供相对路径，防止后期迁移服务器后，所有的头像数据全部不显示了）
  ##nginxHost: 10.12.97.34
  ###nginx端口
  ##nginxPort: 80
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  - 10.11.24.138:22122
upload:
   picture:
     mast: jpg,png








