server:
  port: 8772

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-tools
  servlet:
    multipart:
      max-request-size: 1000Mb
      max-file-size: 1000Mb
  datasource:
    password: 123456
    tomcat:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait: 10000
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.11.24.136:1521:arltr
    username: lark_tool
mybatis:
  mapper-locations: classpath:mapper/*.xml