server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

spring:
  profiles:
    active: dev
  application:
    name: ace-config-server
  cloud:
    config:
      server:
        git:
          uri: http://10.12.97.30:3000/LiamShaw/aceconfig-test.git
          search-paths: /
          username:
          password:
      label: master